*******************************************************************************
****** TSPCFF schematic TSPCFF_LIB  <vs>  TSPCFF layout TSPCFF_LIB
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(INV schematic TSPCFF_LIB, _) Cell                2       0*
(g45p1svt) MOS                                    5       7*
(g45n1svt) MOS                                    4       6*
                                             ------  ------
Total                                            11      13

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    6       6           4       4
(g45p1svt) MOS                                    7       7           3       3
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:SerMos2#1) MosBlk                       -       -           2       2
                                             ------  ------      ------  ------
Total                                            13      13          10      10

Schematic and Layout Match
