0 0 dataAuditErrors
473 0 SI g45inda connectionErrors
474 0 SI g45inda spacingErrors
475 0 SI g45inda innerDiameterErrors
476 0 SI g45inda widthErrors
490 0 ptap_StampErrorFloat
491 0 ptap_StampErrorMult
492 0 ptap_StampErrorConnect
497 0 pwell_StampErrorFloat
498 0 pwell_StampErrorMult
499 0 pwell_StampErrorConnect
504 0 ntap_StampErrorFloat
505 0 ntap_StampErrorMult
506 0 ntap_StampErrorConnect
511 0 nwell_conn_StampErrorFloat
512 0 nwell_conn_StampErrorMult
513 0 nwell_conn_StampErrorConnect
518 0 nb_tap_StampErrorFloat
519 0 nb_tap_StampErrorMult
520 0 nb_tap_StampErrorConnect
525 0 Nburied_StampErrorFloat
526 0 Nburied_StampErrorMult
527 0 Nburied_StampErrorConnect
532 0 ptap_StampErrorFloat
533 0 ptap_StampErrorMult
534 0 ptap_StampErrorConnect
539 0 pwell_StampErrorFloat
540 0 pwell_StampErrorMult
541 0 pwell_StampErrorConnect
546 0 ntap_StampErrorFloat
547 0 ntap_StampErrorMult
548 0 ntap_StampErrorConnect
553 0 nwell_conn_StampErrorFloat
554 0 nwell_conn_StampErrorMult
555 0 nwell_conn_StampErrorConnect
560 0 nb_tap_StampErrorFloat
561 0 nb_tap_StampErrorMult
562 0 nb_tap_StampErrorConnect
567 0 Nburied_StampErrorFloat
568 0 Nburied_StampErrorMult
569 0 Nburied_StampErrorConnect
585 0 all malformed SI g45inda
2621 0 malformed device RECOG_NEW_T?472
2622 0 malformed device _nmos1v
2623 0 malformed device _nmos1v_hvt
2624 0 malformed device _nmos1v_lvt
2625 0 malformed device _nmos_12_native
2626 0 malformed device _nmos_25
2627 0 malformed device _nmos_25_native
2628 0 malformed device _nmoscap1v
2629 0 malformed device _nmoscap2v
2630 0 malformed device _pmos1v
2631 0 malformed device _pmos1v_hvt
2632 0 malformed device _pmos1v_lvt
2633 0 malformed device _pmos2v
2634 0 malformed device _pmoscap1v
2635 0 malformed device _pmoscap2v
2636 0 malformed device _resm1
2637 0 malformed device _resm2
2638 0 malformed device _resm3
2639 0 malformed device _resm4
2640 0 malformed device _resm5
2641 0 malformed device _resm6
2642 0 malformed device _resm7
2643 0 malformed device _resm8
2644 0 malformed device _resm9
2645 0 malformed device _resm10
2646 0 malformed device _resm11
2647 0 malformed device _ressndiff
2648 0 malformed device _resnsndiff
2649 0 malformed device _ressnpoly
2650 0 malformed device _ressnpoly_nw
2651 0 malformed device _resnsnpoly
2652 0 malformed device _resnsnpoly_nw
2653 0 malformed device _resspdiff
2654 0 malformed device _resnspdiff
2655 0 malformed device _ressppoly
2656 0 malformed device _ressppoly_nw
2657 0 malformed device _resnsppoly
2658 0 malformed device _resnsppoly_nw
2659 0 malformed device _resnwsti
2660 0 malformed device _resnwoxide
2661 0 malformed device _ndio
2662 0 malformed device _ndio_lvt
2663 0 malformed device _ndio_hvt
2664 0 malformed device _ndio_nvt
2665 0 malformed device _ndio_2v
2666 0 malformed device _ndio_2v_nvt
2667 0 malformed device _pdio
2668 0 malformed device _pdio_lvt
2669 0 malformed device _pdio_hvt
2670 0 malformed device _pdio_2v
2671 0 malformed device _vpnp2
2672 0 malformed device _vpnp5
2673 0 malformed device _vpnp10
2674 0 malformed device _npn2
2675 0 malformed device _npn5
2676 0 malformed device _npn10
2677 0 malformed device _mimcap
2678 0 malformed device _ind_s
3005 0 unstable device for _ind_s_Device_58
3006 0 unpreserved device _ind_s_Device_58
3007 0 unstable device for _mimcap_CAP_57
3008 0 unpreserved device _mimcap_CAP_57
3009 0 unstable device for _npn10_BJT_56
3010 0 unpreserved device _npn10_BJT_56
3011 0 unstable device for _npn5_BJT_55
3012 0 unpreserved device _npn5_BJT_55
3013 0 unstable device for _npn2_BJT_54
3014 0 unpreserved device _npn2_BJT_54
3015 0 unstable device for _vpnp10_BJT_53
3016 0 unpreserved device _vpnp10_BJT_53
3017 0 unstable device for _vpnp5_BJT_52
3018 0 unpreserved device _vpnp5_BJT_52
3019 0 unstable device for _vpnp2_BJT_51
3020 0 unpreserved device _vpnp2_BJT_51
3021 0 unstable device for _pdio_2v_DIODE_50
3022 0 unpreserved device _pdio_2v_DIODE_50
3023 0 unstable device for _pdio_hvt_DIODE_49
3024 0 unpreserved device _pdio_hvt_DIODE_49
3025 0 unstable device for _pdio_lvt_DIODE_48
3026 0 unpreserved device _pdio_lvt_DIODE_48
3027 0 unstable device for _pdio_DIODE_47
3028 0 unpreserved device _pdio_DIODE_47
3029 0 unstable device for _ndio_2v_nvt_DIODE_46
3030 0 unpreserved device _ndio_2v_nvt_DIODE_46
3031 0 unstable device for _ndio_2v_DIODE_45
3032 0 unpreserved device _ndio_2v_DIODE_45
3033 0 unstable device for _ndio_nvt_DIODE_44
3034 0 unpreserved device _ndio_nvt_DIODE_44
3035 0 unstable device for _ndio_hvt_DIODE_43
3036 0 unpreserved device _ndio_hvt_DIODE_43
3037 0 unstable device for _ndio_lvt_DIODE_42
3038 0 unpreserved device _ndio_lvt_DIODE_42
3039 0 unstable device for _ndio_DIODE_41
3040 0 unpreserved device _ndio_DIODE_41
3041 0 unstable device for _resnwoxide_RES_40
3042 0 unpreserved device _resnwoxide_RES_40
3043 0 unstable device for _resnwsti_RES_39
3044 0 unpreserved device _resnwsti_RES_39
3045 0 unstable device for _resnsppoly_nw_RES_38
3046 0 unpreserved device _resnsppoly_nw_RES_38
3047 0 unstable device for _resnsppoly_RES_37
3048 0 unpreserved device _resnsppoly_RES_37
3049 0 unstable device for _ressppoly_nw_RES_36
3050 0 unpreserved device _ressppoly_nw_RES_36
3051 0 unstable device for _ressppoly_RES_35
3052 0 unpreserved device _ressppoly_RES_35
3053 0 unstable device for _resnspdiff_RES_34
3054 0 unpreserved device _resnspdiff_RES_34
3055 0 unstable device for _resspdiff_RES_33
3056 0 unpreserved device _resspdiff_RES_33
3057 0 unstable device for _resnsnpoly_nw_RES_32
3058 0 unpreserved device _resnsnpoly_nw_RES_32
3059 0 unstable device for _resnsnpoly_RES_31
3060 0 unpreserved device _resnsnpoly_RES_31
3061 0 unstable device for _ressnpoly_nw_RES_30
3062 0 unpreserved device _ressnpoly_nw_RES_30
3063 0 unstable device for _ressnpoly_RES_29
3064 0 unpreserved device _ressnpoly_RES_29
3065 0 unstable device for _resnsndiff_RES_28
3066 0 unpreserved device _resnsndiff_RES_28
3067 0 unstable device for _ressndiff_RES_27
3068 0 unpreserved device _ressndiff_RES_27
3069 0 unstable device for _resm11_RES_26
3070 0 unpreserved device _resm11_RES_26
3071 0 unstable device for _resm10_RES_25
3072 0 unpreserved device _resm10_RES_25
3073 0 unstable device for _resm9_RES_24
3074 0 unpreserved device _resm9_RES_24
3075 0 unstable device for _resm8_RES_23
3076 0 unpreserved device _resm8_RES_23
3077 0 unstable device for _resm7_RES_22
3078 0 unpreserved device _resm7_RES_22
3079 0 unstable device for _resm6_RES_21
3080 0 unpreserved device _resm6_RES_21
3081 0 unstable device for _resm5_RES_20
3082 0 unpreserved device _resm5_RES_20
3083 0 unstable device for _resm4_RES_19
3084 0 unpreserved device _resm4_RES_19
3085 0 unstable device for _resm3_RES_18
3086 0 unpreserved device _resm3_RES_18
3087 0 unstable device for _resm2_RES_17
3088 0 unpreserved device _resm2_RES_17
3089 0 unstable device for _resm1_RES_16
3090 0 unpreserved device _resm1_RES_16
3091 0 unstable device for _pmoscap2v_MOS_15
3092 0 unpreserved device _pmoscap2v_MOS_15
3093 0 unstable device for _pmoscap1v_MOS_14
3094 0 unpreserved device _pmoscap1v_MOS_14
3095 0 unstable device for _pmos2v_MOS_13
3096 0 unpreserved device _pmos2v_MOS_13
3097 0 unstable device for _pmos1v_lvt_MOS_12
3098 0 unpreserved device _pmos1v_lvt_MOS_12
3099 0 unstable device for _pmos1v_hvt_MOS_11
3100 0 unpreserved device _pmos1v_hvt_MOS_11
3101 0 unstable device for _pmos1v_MOS_10
3102 0 unpreserved device _pmos1v_MOS_10
3103 0 unstable device for _nmoscap2v_MOS_9
3104 0 unpreserved device _nmoscap2v_MOS_9
3105 0 unstable device for _nmoscap1v_MOS_8
3106 0 unpreserved device _nmoscap1v_MOS_8
3107 0 unstable device for _nmos_25_native_MOS_7
3108 0 unpreserved device _nmos_25_native_MOS_7
3109 0 unstable device for _nmos_25_MOS_6
3110 0 unpreserved device _nmos_25_MOS_6
3111 0 unstable device for _nmos_12_native_MOS_5
3112 0 unpreserved device _nmos_12_native_MOS_5
3113 0 unstable device for _nmos1v_lvt_MOS_4
3114 0 unpreserved device _nmos1v_lvt_MOS_4
3115 0 unstable device for _nmos1v_hvt_MOS_3
3116 0 unpreserved device _nmos1v_hvt_MOS_3
3117 0 unstable device for _nmos1v_MOS_2
3118 0 unpreserved device _nmos1v_MOS_2
3119 0 unstable device for DEVICE_LAYER_RECOG_NEW_T?472_SI_1
3120 0 unpreserved device DEVICE_LAYER_RECOG_NEW_T?472_SI_1
